name: Flutter Workflow

on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:    
      - main
      - master
permissions: read-all
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      # - name: Install dependencies
      #   run: flutter pub get
      - run: flutter --version
        
        
      - name: Run unit tests
        run: flutter test --coverage

      # - name: Run integration tests
      #   uses: reactivecircus/android-emulator-runner@v1
      #   with:
      #     api-level: 29
      #     script: flutter drive --driver=test_driver/main_test.dart --target integration_test/app_test.dart

      - run: flutter build apk --release


      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
      - id: read-version
        uses: NiklasLehnfeld/flutter-version-number-action@main
        with:
          file-path: pubspec.yaml
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk"
          tag: v${{ steps.read-version.outputs.version-number }}
          token: ${{ secrets.TOKEN }}
          generateReleaseNotes: true
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Build Changelog"
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          configuration: ".github/workflows/configs/configuration.json"
          ignorePreReleases: "false"
        env:
          TOKEN: ${{ secrets.TOKEN }}
 
 
  build-windows-standard:
    name: "Build Windows standard"
    runs-on: windows-latest
    env:
      TOKEN: ${{ secrets.TOKEN }}

    steps:
      - uses: actions/checkout@v2.4.0

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2.6.1
        with:
          channel: "stable"

      - name: Enable desktop
        run: flutter config --enable-windows-desktop

      - name: Install Cider
        run: flutter pub global activate cider

      - name: Set new Flutter version
        run: cider version ${{ github.event.release.tag_name }}

      - name: Set release changelog
        run: cider release

      - name: Generate MSIX-compatible version
        uses: ashley-taylor/regex-property-action@1.2
        id: msixver
        with:
          value: ${{ github.event.release.tag_name }}
          regex: (\-\w+)|(\+\w+)
          replacement: ""

      - name: Write MSIX
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: pubspec.yaml
          contents: |
            msix_config:
              display_name: Blog App
              publisher_display_name: Shreeman Arjun
              identity_name: com.arjun.blog
              msix_version: ${{steps.msixver.outputs.value }}.0
              logo_path: assets/ic_launcher/ic_launcher.png
              architecture: x64
              capabilities: "internetClient,removableStorage"
              store: false
          write-mode: append

      - name: Flutter get packages
        run: flutter pub get

      - name: Build Runner & version
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Flutter build app
        run: flutter build windows

      - name: Create MSIX
        run: flutter pub run msix:create

      - name: Compress artifacts
        run: tar.exe -a -c -f windows-${{ github.event.release.tag_name }}.zip build/windows/Runner/release

      - name: Upload artifacts to release
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.TOKEN }}
          file: windows-${{ github.event.release.tag_name }}.zip
          tag: ${{ github.ref }}

      - name: Upload MSIX to release
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.TOKEN }}
          file: build/windows/Runner/release/sidekick.msix
          asset_name: sidekick-windows-${{ github.event.release.tag_name }}.msix
          tag: ${{ github.ref }}